### ISSUE TITLE
Bug: Input box remains in error state in "Leaves on a Merkle Tree" tutorial

### ISSUE THREAD

**Issue by nathanzebedee** [helius-labs/pyre#13]
**Issue Summary**:

In the tutorial "Leaves on a Merkle Tree", once an erroneous answer is provided, the input box remains stuck in the error state. After this occurs, the input box no longer shows error messages regardless of the user input. Additionally, providing the correct answer still results in an error message.

**Steps to reproduce**:

Launch the app and navigate to the "Leaves on a Merkle Tree" tutorial.
Provide an incorrect answer to one of the questions.
Notice that the input box goes into an error state.
Try inputting any other answers, incorrect or correct.

**Expected Behavior**:

The input box should reset from the error state after a new answer is input. Providing the correct answer should not result in an error message.

**Actual Behavior**:

The input box remains in the error state regardless of any further input. Even when the correct answer is provided, an error message is thrown.

**Comment by Tidelaw** [comment]
Thanks for the feedback! I'll add something to trigger the shake animation once again on multiple incorrect answers. Could you provide the specific context (cNFT mint address) that you think the question has wrong? I just tested it and it seems accurate according to XRay.

**Comment by nathanzebedee** [comment]
I looked up the merkle tree address on solana explorer. when i pasted the `Current Number of Leaves` value, it threw an error: https://explorer.solana.com/address/6AVRHWpfzNvogbYtCh51v12B8YGmjLsrgErJpVQUUdYp/concurrent-merkle-tree

**Comment by Tidelaw** [comment]
Odd, Pyre uses the same method as XRay to check this question, https://xray.helius.xyz/account/6AVRHWpfzNvogbYtCh51v12B8YGmjLsrgErJpVQUUdYp/concurrent-merkle-tree looks like the values differ by 1, perhaps this is an issue with something else, what method are you using programatically to find the current number of leaves?
