### ISSUE TITLE
Bug: User unable to navigate back to tutorials menu, page refresh resets app state

### ISSUE THREAD

**Issue by nathanzebedee** [helius-labs/pyre#14]
**Issue Summary**:

The user is unable to navigate back to the main menu of tutorials from within a tutorial. Furthermore, refreshing the page causes the entire application state to reset, pushing the user back to the landing page and disrupting any progress they have made.

**Steps to reproduce**:

Launch the app and navigate to the tutorials section.
Select and start any tutorial.
Attempt to navigate back to the main menu of tutorials.
Notice the inability to navigate back.
Refresh the page.

**Expected Behavior**:

The user should be able to navigate back to the tutorials menu from within a tutorial without losing their progress. Refreshing the page should maintain the user's current state in the tutorial, not reset the entire application.

**Actual Behavior**:

Attempting to navigate back to the tutorials menu is unsuccessful. Refreshing the page resets the app state and pushes the user back to the landing page, causing a loss of progress in the tutorial.

**Comment by Tidelaw** [comment]
What do you mean by the main menu of tutorials? There is only one tutorial, it's the one titled Native Balance, all components should be able to go back to the menu. Could you attach an image of the page, or name the component in which you are not able to go back from?

**Comment by nathanzebedee** [comment]
https://www.loom.com/share/8a7fd2e3542243aaacd5f22f2bcd4862?sid=b4de2b96-b159-49d9-be51-bbdc0b90b908

**Comment by Tidelaw** [comment]
Sorry about the light theme! Did that a while ago but it turned out pretty bad and I forgot to remove it entirely, will do now. Thanks for spotting and raising an issue! Will definitely explore expanding it beyond a 1 page thing and I can see the confusion by reloading.
