### ISSUE TITLE
[xnft] Wallet Address is not copyable

### ISSUE THREAD

**Issue by birdmanmandbir** [helius-labs/pyre#30]
The error in browser console is: 
```
Uncaught (in promise) DOMException: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
    at onClick (https://pyre.helius.xyz/_next/static/chunks/pages/index-78298e5fb06d9dce.js:1:16122)
    at Object.eU (https://pyre.helius.xyz/_next/static/chunks/framework-2c79e2a64abdb08b.js:9:14912)
```
<img width="620" alt="image" src="https://github.com/helius-labs/pyre/assets/48193000/79451e7c-8243-4d53-ad52-d38255abe648">

**Comment by hagitran** [comment]
Hi, I believe this issue stems from a setting on your personal chrome browser as it's working fine on my end. I'd suggest following the link mentioned in the error in order to clear this up.

**Comment by birdmanmandbir** [comment]
> Hi, I believe this issue stems from a setting on your personal chrome browser as it's working fine on my end. I'd suggest following the link mentioned in the error in order to clear this up.

This is not an issue with Pyre; I opened Pyre using the xNFT, but the outer iframe did not have the `allow="clipboard-read; clipboard-write"` attribute set, so the Pyre copy function cannot be used within the xNFT iframe.
Reference: https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard

**Comment by birdmanmandbir** [comment]
[Enable clipboard writes for xnfts by ph101pp · Pull Request #2601 · coral-xyz/backpack](https://github.com/coral-xyz/backpack/pull/2601/files) don't know why this pull request didn't take effect.

**Comment by hagitran** [comment]
This issue is resolved in terms of Pyre then?

**Comment by birdmanmandbir** [comment]
> This issue is resolved in terms of Pyre then?

Yes, this is not an issue of pyre
